// <auto-generated />
using AssetsSquirrel.Plugins.EFCoreSqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetsSquirrel.Plugins.EFCoreSqlServer.Migrations
{
    [DbContext(typeof(AssetsSquirrelContext))]
    [Migration("20250514124041_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetSquirrel.CoreBusiness.DictionaryEquipment", b =>
                {
                    b.Property<int>("DictionaryEquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DictionaryEquipmentId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DictionaryEquipmentId");

                    b.ToTable("DictionaryEquipments");

                    b.HasData(
                        new
                        {
                            DictionaryEquipmentId = 1,
                            Description = "",
                            IsActive = true,
                            Name = "AccessPoint"
                        },
                        new
                        {
                            DictionaryEquipmentId = 2,
                            Description = "",
                            IsActive = true,
                            Name = "Drukarka etykiet"
                        },
                        new
                        {
                            DictionaryEquipmentId = 3,
                            Description = "",
                            IsActive = true,
                            Name = "Drukarka fiskalna"
                        },
                        new
                        {
                            DictionaryEquipmentId = 4,
                            Description = "",
                            IsActive = true,
                            Name = "Dysk zewnętrzny"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
